In [1]:
import numpy as np

def cholesky(A):#cholesky(A): Define la función que realiza la factorización de Cholesky.


    n = A.shape[0]  # Obtener el tamaño de la matriz
    L = np.zeros((n, n))  # Inicializar la matriz L con ceros
    # L será la matriz triangular inferior que buscamos

    for i in range(n):
        for j in range(i + 1):  #tera a través de la matriz L, calculando sus elementos fila por fila y columna por columna.
                                #La iteración se realiza solo hasta la diagonal porque L es triangular inferior.
            suma = 0
            for k in range(j):
                suma += L[i, k] * L[j, k]#Calcula la suma de los productos de los elementos de L en la fila i y la columna j.

            if i == j: #Si estamos en la diagonal, calculamos el elemento diagonal de L.
                # Elemento diagonal
                L[i, j] = np.sqrt(A[i, i] - suma)
            else: #Si no estamos en la diagonal, calculamos el elemento fuera de la diagonal de L
                # Elemento fuera de la diagonal
                L[i, j] = (A[i, j] - suma) / L[j, j]
    return L

A = np.array([[2, -1, 0], [-1, 2, -1], [0, -1, 2]])  # Matriz simétrica definida positiva
L = cholesky(A)
print(L)
B = np.array([[4, 1, 1, 1], [1, 3, -1, -1],[1, -1, 2, 0], [1, 1, 0, 2]])
L = cholesky(B)
print(L)
C = np.array([[4, 1, -1, 0], [1, 3, -1, 0], [-1, -1, 5, 2], [0, 0, 2, 4]])
L = cholesky(C)
print(L)
D = np.array([[6, 2, 1, -1], [2, 4, 1, 0],[1, 1, 4, -1], [-1, 0, -1, 3]])
L = cholesky(D)
print(L)

[[ 1.41421356  0.          0.        ]
 [-0.70710678  1.22474487  0.        ]
 [ 0.         -0.81649658  1.15470054]]
[[ 2.          0.          0.          0.        ]
 [ 0.5         1.6583124   0.          0.        ]
 [ 0.5        -0.75377836  1.08711461  0.        ]
 [ 0.5         0.45226702  0.0836242   1.24034735]]
[[ 2.          0.          0.          0.        ]
 [ 0.5         1.6583124   0.          0.        ]
 [-0.5        -0.45226702  2.13200716  0.        ]
 [ 0.          0.          0.93808315  1.76635217]]
[[ 2.44948974  0.          0.          0.        ]
 [ 0.81649658  1.82574186  0.          0.        ]
 [ 0.40824829  0.36514837  1.92353841  0.        ]
 [-0.40824829  0.18257419 -0.46788772  1.60657433]]
