In [17]:
import numpy as np

def eliminacion_gaussiana_pivoteo_parcial(A, b):

  n = len(b)
  A_escalonada = np.copy(A)  # Para no modificar la matriz original
  b_escalonado = np.copy(b)

  for k in range(n - 1):
    # Pivoteo parcial
    max_index = k
    for i in range(k + 1, n):
      if abs(A_escalonada[i, k]) > abs(A_escalonada[max_index, k]):
          max_index = i

    if max_index != k: #Buscamos el elemento con mayor valor absoluto en la columna k debajo de la diagonal
                      #Si encontramos uno mayor que el actual, intercambiamos las filas para ponerlo como pivote
      A_escalonada[[k, max_index]] = A_escalonada[[max_index, k]] #Intercambia filas de A
      b_escalonado[[k, max_index]] = b_escalonado[[max_index, k]] #Intercambia filas de b


    # Eliminación
    for i in range(k + 1, n): #Para cada fila debajo del pivote:
                              #Calculamos un factor de eliminación
                              #Restamos múltiplos de la fila pivote para crear ceros debajo del pivote
        factor = A_escalonada[i, k] / A_escalonada[k, k]
        A_escalonada[i, k:] = A_escalonada[i, k:] - factor * A_escalonada[k, k:]
        b_escalonado[i] = b_escalonado[i] - factor * b_escalonado[k]

  # Sustitución hacia atrás
  x = np.zeros(n)
  for i in range(n - 1, -1, -1):
    suma = 0
    for j in range(i + 1, n):
      suma += A_escalonada[i, j] * x[j]

    if A_escalonada[i, i] == 0: # Verifica si hay un cero en la diagonal
      return None # Si hay un cero en la diagonal, no se puede resolver con este metodo

    x[i] = (b_escalonado[i] - suma) / A_escalonada[i, i]

  return x, A_escalonada


In [28]:
import numpy as np

def factorizacion_lu_pivoteo_total(A):

    n = A.shape[0]
    if n != A.shape[1]:
        return None  # La matriz debe ser cuadrada

    P = np.identity(n)
    L = np.zeros((n, n))
    U = np.copy(A)

    for k in range(n - 1):
        # Pivoteo total: encontrar el elemento de mayor valor absoluto en la submatriz restante
        max_valor = 0
        fila_max = k
        col_max = k
        for i in range(k, n):
            for j in range(k, n):
                if abs(U[i, j]) > max_valor:
                    max_valor = abs(U[i, j])
                    fila_max = i
                    col_max = j

        # Intercambiar filas
        if fila_max != k:
            U[[k, fila_max]] = U[[fila_max, k]]
            P[[k, fila_max]] = P[[fila_max, k]]
            if k > 0:  # Ajustar la matriz L si es necesario
                L[[k, fila_max], :k] = L[[fila_max, k], :k]

        # Intercambiar columnas (en U y en P)
        if col_max != k:
            U[:, [k, col_max]] = U[:, [col_max, k]]
            P[:, [k, col_max]] = P[:, [col_max, k]]  # Actualizar P

        # Eliminación gaussiana
        for i in range(k + 1, n):
            factor = U[i, k] / U[k, k]
            U[i, k:] = U[i, k:] - factor * U[k, k:]
            L[i, k] = factor

    #Completar la diagonal de L con unos
    np.fill_diagonal(L,1)
    return P, L, U

# Define A outside the function
A = np.array([[1,0,0,0,1], [-1,1,0,0,1], [-1,-1,1,0,1], [-1,-1,-1,1,1], [-1,-1,-1,-1,1]])

#Now you can call the function with A
P, L, U = factorizacion_lu_pivoteo_total(A)

print("Matriz A:")
print(A)
print("\nMatriz P:")
print(P)
print("\nMatriz L:")
print(L)
print("\nMatriz U:")
print(U)

Matriz A:
[[ 1  0  0  0  1]
 [-1  1  0  0  1]
 [-1 -1  1  0  1]
 [-1 -1 -1  1  1]
 [-1 -1 -1 -1  1]]

Matriz P:
[[1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]
 [0. 1. 0. 0. 0.]]

Matriz L:
[[ 1.  0.  0.  0.  0.]
 [-1.  1.  0.  0.  0.]
 [-1.  1.  1.  0.  0.]
 [-1.  1.  1.  1.  0.]
 [-1.  1.  1.  1.  1.]]

Matriz U:
[[ 1  1  0  0  0]
 [ 0  2  1  0  0]
 [ 0  0 -2  1  0]
 [ 0  0  0 -2  1]
 [ 0  0  0  0 -2]]
