Ejercicio 23

In [1]:
import numpy as np

In [128]:

# Definimos la variable para almacenar cada valor de ε
Val_ε=[]

# Definimos la variable donde se almacenan todas las matrices para cada
# Valor de ε
Mat=[]

# Definimos la variable donde se almacenará cada vector resultante
Vect_r = []


'''
Definimos a todos los valores de ε con un ciclo 'for':
ε = 10^(−2k), con k = 1, · · · , 10.
'''

# Tomamos el rango de k entre 1 y 10
for k in range(1, 11):
  # La definición de ε
  ε = 10**(-2 * k)
  Val_ε.append(ε)
  # se almacenan los valores de ε para cada k, en una lista

# Ahora usamos los valores de ε para hacer cada matriz con un valor
# diferente para cada ε
for i in Val_ε:
  # Definimos la matriz A que tiene a cada valor de ε
  A = np.array([[ε, 1], [1, 1]])
  # agregamos cada matriz a una lista de matrices
  Mat.append(A)


'''
Ahora definimos al vector resultante del sistema
usando los valores que ya calculamos para ε
'''

for i in Val_ε:
  # Definimos al vector resultante
  V = np.array([1+i , 2])
  # agregamos cada vector a la lista de vectores
  Vect_r.append(V)

'''
definamos las matrices aumentadas

'''
for A, b_i in zip(Mat, Vect_r):
    aumentada = []  # Lista para una matriz aumentada individual
    for fila, b in zip(A, b_i):
        # Concatenamos cada fila de la matriz A con el valor bi del vector b
        fila_aumentada = fila + [b_i]
        aumentada.append(fila_aumentada)
    matrices_aumentadas.append(aumentada)

# Convertir las matrices en matrices triangulares superiores
# print(np.array(matrices_aumentadas[0:10]))
MTS = np.triu(np.array(matrices_aumentadas[0:10]))


# Ahora recuperemos el vector nuevo, despues de volver a la matriz, triangular
# superior

# En esta variable almacenamos el vector nuevo
N_vect = []

# Iteramos en cada matriz aumentada
for matriz in MTS:
    vector_n = []
    for fila in matriz:
        vector_n.append(fila[-1])
    N_vect.append(vector_n)


# Ahora recuperamos las nuevas matrices, triangulares S.
Nueva_mat = []
# Iteramos en cada matriz aumentada
for m in MTS:
    N_mat = []
    for fila in m:
        N_mat.append(fila[:-1])  # Excluir la última entrada de cada fila
    Nueva_mat.append(N_mat)



'''
Ahora usaremos la funcion para la sustitucion hacia atras
que se trabajó en clase, pero con modificaciones para que acepte
listas de matrices y vectores
'''

def SustitucionAtras(lista_matrices, lista_vectores):
    """
    Resuelve múltiples sistemas de ecuaciones usando sustitución hacia atrás.

    Parámetros:
    -----------
    lista_matrices : list of lists
        Lista de matrices triangulares superiores (cada una como lista de listas o np.array).
    lista_vectores : list of lists
        Lista de vectores independientes correspondientes a cada matriz.

    Retorna:
    --------
    soluciones : list of np.ndarray
        Lista de soluciones para cada sistema.

    """
    soluciones = []

    for mat, b in zip(lista_matrices, lista_vectores):
        mat = np.array(mat)
        b = np.array(b)
        n = mat.shape[0]
        x = np.zeros(n)

        for i in range(n - 1, -1, -1):
            suma = 0.0
            for j in range(i + 1, n):
                suma += mat[i, j] * x[j]
            x[i] = (b[i] - suma) / mat[i, i]

        soluciones.append(x)

    return soluciones
'''
Soluciones del sistema:
'''
# primero nos aseguramos de que todos los datos sean arreglos de numpy
Vector_final = []

for i in N_vect:
  V= np.array(i)
  Vector_final.append(V)

Matriz_final = []
for j in Nueva_mat:
  mt = np.array(j)
  Matriz_final.append(mt)

# imprimimos los resultados
SustitucionAtras(Matriz_final, Vector_final)



[array([-99.,   2.]),
 array([-9.999e+03,  2.000e+00]),
 array([-9.99999e+05,  2.00000e+00]),
 array([-9.9999999e+07,  2.0000000e+00]),
 array([-1.e+10,  2.e+00]),
 array([-1.e+12,  2.e+00]),
 array([-1.e+14,  2.e+00]),
 array([-1.e+16,  2.e+00]),
 array([-1.e+18,  2.e+00]),
 array([-1.e+20,  2.e+00])]

a medida que epsilon decrece, la soluciones nuevas, se alejan más de la solucion original