# Ejercicio 24

In [6]:
# 24a

import numpy as np

# definimos una función para crear una matriz de 5 diagonales
def crear_matriz(n):
    A = np.zeros((n, n))  # Inicializa matriz nxn de ceros

    for i in range(n):
        if i > 1:
            A[i, i-2] = 1         # Segunda diagonal por endebajo
        if i > 0:
            A[i, i-1] = -4        # Primera diagonal por debajo de la principal
        A[i, i] = 6               # Diagonal principal
        if i < n-1:
            A[i, i+1] = -4        # Primera diagonal por encima de la principal
        if i < n-2:
            A[i, i+2] = 1         # Segunda diagonal por encima

  # Definimos los valores especificos de las primeras entradas de las diagonales
    A[0, 0] = 9
    A[n-2, n-2] = 5
    A[n-1, n-1] = 1

    A[n-1, n-2] = -2
    A[n-2, n-1] = -2
    A[n-1, n-3] = 1
    A[n-3, n-1] = 1

    return A

m=crear_matriz(100)
b=np.ones(100)

def SustitucionDelante(Mat, b):
    """
    Realiza la sustitución hacia adelante para resolver un sistema de ecuaciones lineales
    representado por una matriz triangular inferior.

    Parámetros:
    -----------
    Mat : numpy.ndarray
        Una matriz triangular inferior de tamaño n x n.
    b : numpy.ndarray
        Un vector de términos independientes de tamaño n.

    Retorna:
    --------
    x : numpy.ndarray
        Un vector solución de tamaño n que satisface la ecuación Mat @ x = b.

    Descripción:
    ------------
    Esta función resuelve un sistema de ecuaciones lineales de la forma Mat @ x = b,
    donde Mat es una matriz triangular inferior. Utiliza el método de sustitución hacia adelante,
    comenzando desde la primera fila de la matriz y avanzando hacia la última.

    Ejemplo:
    --------
    >>> Mat = np.array([[1, 0, 0],
    ...                 [2, 3, 0],
    ...                 [4, 5, 6]])
    >>> b = np.array([1, 8, 32])
    >>> SustitucionDelante(Mat, b)
    array([1., 2., 3.])
    """
    n = Mat.shape[0]
    x = np.zeros(n)

    for i in range(n):
        SumCum = 0.0
        for j in range(i):
            SumCum += Mat[i, j] * x[j]
        x[i] = (b[i] - SumCum) / Mat[i, i]

    return x



def SustitucionAtras(Mat, b):
    """
    Realiza la sustitución hacia atrás para resolver un sistema de ecuaciones lineales
    representado por una matriz triangular superior.

    Parámetros:
    -----------
    Mat : numpy.ndarray
        Una matriz triangular superior de tamaño n x n.
    b : numpy.ndarray
        Un vector de términos independientes de tamaño n.

    Retorna:
    --------
    x : numpy.ndarray
        Un vector solución de tamaño n que satisface la ecuación Mat @ x = b.

    Descripción:
    ------------
    Esta función resuelve un sistema de ecuaciones lineales de la forma Mat @ x = b,
    donde Mat es una matriz triangular superior. Utiliza el método de sustitución hacia atrás,
    comenzando desde la última fila de la matriz y avanzando hacia la primera.

    Ejemplo:
    --------
    >>> Mat = np.array([[3, 2, 1],
    ...                 [0, 2, 1],
    ...                 [0, 0, 1]])
    >>> b = np.array([6, 4, 1])
    >>> SustitucionAtras(Mat, b)
    array([1., 1., 1.])
    """
    n = Mat.shape[0]
    x = np.zeros(n)

    for i in range(n-1, -1, -1):
        SumCum = 0.0
        for j in range(i+1, n):
            SumCum += Mat[i, j] * x[j]
        x[i] = (b[i] - SumCum) / Mat[i, i]

    return x



def LU(A):
  U=np.copy(A)
  L=np.eye(A.shape[0])

  for i in range(A.shape[0]):
    Li=np.eye(A.shape[0])
    for j in range(i+1,A.shape[0]):
      Li[j,i]=-U[j,i]/U[i,i]
      L[j,i]=U[j,i]/U[i,i]
    U=Li@U
  return L,U


def SolverLU(A,b):
  L,U=LU(A)
  # El sistema que se resuelve es Ly=b
  y=SustitucionDelante(L, b)
  # El sistema que se resuelve es Ux=y
  x=SustitucionAtras(U, y)

  return x


Sol=SolverLU(m,b)
Sol


array([1.26250000e+03, 7.47500000e+03, 1.85385000e+04, 3.43550000e+04,
       5.48275000e+04, 7.98600000e+04, 1.09357500e+05, 1.43226000e+05,
       1.81372500e+05, 2.23705000e+05, 2.70132500e+05, 3.20565000e+05,
       3.74913500e+05, 4.33090000e+05, 4.95007500e+05, 5.60580000e+05,
       6.29722500e+05, 7.02351000e+05, 7.78382500e+05, 8.57735000e+05,
       9.40327500e+05, 1.02608000e+06, 1.11491350e+06, 1.20675000e+06,
       1.30151250e+06, 1.39912500e+06, 1.49951250e+06, 1.60260100e+06,
       1.70831750e+06, 1.81659000e+06, 1.92734750e+06, 2.04052000e+06,
       2.15603850e+06, 2.27383500e+06, 2.39384250e+06, 2.51599500e+06,
       2.64022750e+06, 2.76647600e+06, 2.89467750e+06, 3.02477000e+06,
       3.15669250e+06, 3.29038500e+06, 3.42578850e+06, 3.56284500e+06,
       3.70149750e+06, 3.84169000e+06, 3.98336750e+06, 4.12647600e+06,
       4.27096250e+06, 4.41677500e+06, 4.56386250e+06, 4.71217500e+06,
       4.86166350e+06, 5.01228000e+06, 5.16397750e+06, 5.31671000e+06,
      

In [10]:
# 24b

def resolver_banda(A, b):
    """
    Resuelve Ax = b donde A es una matriz pentadiagonal.
    Esta función usa eliminación Gaussiana especializada para matrices banda.

    Parámetros:
    - A: np.ndarray, matriz pentadiagonal (n x n)
    - b: np.ndarray, vector del lado derecho (n,)

    Retorna:
    - x: np.ndarray, solución del sistema Ax = b
    """
    n = len(b)
    A = A.copy()
    b = b.copy()

    # Sustitución hacia adelante
    for i in range(2, n):
        factor1 = A[i, i-2] / A[i-2, i-2]
        A[i, i-1] -= factor1 * A[i-2, i-1]
        A[i, i]   -= factor1 * A[i-2, i]
        if i + 1 < n:
            A[i, i+1] -= factor1 * A[i-2, i+1]
        b[i] -= factor1 * b[i-2]

        factor2 = A[i, i-1] / A[i-1, i-1]
        A[i, i] -= factor2 * A[i-1, i]
        if i + 1 < n:
            A[i, i+1] -= factor2 * A[i-1, i+1]
        b[i] -= factor2 * b[i-1]

    # Sustitución hacia atrás
    x = np.zeros(n)
    x[-1] = b[-1] / A[-1, -1]
    x[-2] = (b[-2] - A[-2, -1] * x[-1]) / A[-2, -2]

    for i in range(n-3, -1, -1):
        x[i] = (b[i] - A[i, i+1]*x[i+1] - A[i, i+2]*x[i+2]) / A[i, i]

    return x

m_n= resolver_banda(m,b)
print(m_n)

[4.20833333e+02 4.10833333e+03 1.26468333e+04 2.59383333e+04
 4.38858333e+04 6.63933333e+04 9.33658333e+04 1.24709333e+05
 1.60330833e+05 2.00138333e+05 2.44040833e+05 2.91948333e+05
 3.43771833e+05 3.99423333e+05 4.58815833e+05 5.21863333e+05
 5.88480833e+05 6.58584333e+05 7.32090833e+05 8.08918333e+05
 8.88985833e+05 9.72213333e+05 1.05852183e+06 1.14783333e+06
 1.24007083e+06 1.33515833e+06 1.43302083e+06 1.53358433e+06
 1.63677583e+06 1.74252333e+06 1.85075583e+06 1.96140333e+06
 2.07439683e+06 2.18966833e+06 2.30715083e+06 2.42677833e+06
 2.54848583e+06 2.67220933e+06 2.79788583e+06 2.92545333e+06
 3.05485083e+06 3.18601833e+06 3.31889683e+06 3.45342833e+06
 3.58955583e+06 3.72722333e+06 3.86637583e+06 4.00695933e+06
 4.14892083e+06 4.29220833e+06 4.43677083e+06 4.58255833e+06
 4.72952183e+06 4.87761333e+06 5.02678583e+06 5.17699333e+06
 5.32819083e+06 5.48033433e+06 5.63338083e+06 5.78728833e+06
 5.94201583e+06 6.09752333e+06 6.25377183e+06 6.41072333e+06
 6.56834083e+06 6.726588

# Comparación:
24b es más eficiente que 24a, ya que no revisamos toda la matriz, sino unicamente las partes que necesitamos, o las diagonales que necesitamos.*

In [30]:
# 24c
def crear_matriz_R(n):
    """
    Crea la matriz triangular superior R con la estructura del inciso 24c.

    Parámetros:
    -----------
    n : Tamaño de la matriz R (n x n)

    Retorna:
    --------
    R : np.ndarray
        Matriz triangular superior R.
    """
    R = np.zeros((n, n))

    # Primer fila
    R[0, 0] = 2
    R[0, 1] = -2
    R[0, 2] = 1

    # Filas interiores
    for i in range(1, n-2):
        R[i, i] = 1
        R[i, i+1] = -2
        R[i, i+2] = 1

    # Penúltima fila
    R[n-2, n-2] = 1
    R[n-2, n-1] = -2

    # Última fila
    R[n-1, n-1] = 1

    return R

R = crear_matriz_R(1000)

# definimos la transpuesta de la matriz R

def transpuesta(matriz):
    """
    Calcula la trasnpuesta de una matriz.

    Parámetros:
    -----------
    matriz :  Matriz original de tamaño m x n

    Retorna:
    --------
    Matriz transnpuesta de tamaño n x m
    """

    filas = len(matriz)
    columnas = len(matriz[0])

    # Creamos una nueva matriz vacía del tamaño transpuesto
    transpuesta = []

    # Recorremos las columnas de la matriz original
    for j in range(columnas):
        nueva_fila = []  # Esta será la nueva fila en la matriz transpuesta

        # Recorremos las filas de la matriz original
        for i in range(filas):
            # Agregamos el elemento transpuesto
            nueva_fila.append(matriz[i][j])

        # Agregamos la fila completa a la matriz transpuesta
        transpuesta.append(nueva_fila)

    return transpuesta
# Creamos una transpuesta a partir de la matriz R
R_t = np.array(transpuesta(R))


<class 'numpy.ndarray'>


In [ ]:
'''
Para verificar que esta facorizacion de A existe vamos a multiplicar a R por R^T
y veamos si nos regresa a A.

Utilizamos el codigo visto en clase para multiplicar matrices.
'''

def MultMat(Mat1, Mat2):
    """
    Realiza la multiplicación de dos matrices.

    Parámetros:
    -----------
    Mat1 : numpy.ndarray
        Una matriz bidimensional de forma (n, m), donde 'n' es el número de filas
        y 'm' es el número de columnas.
    Mat2 : numpy.ndarray
        Una matriz bidimensional de forma (m, p), donde 'm' es el número de filas
        (debe coincidir con el número de columnas de Mat1) y 'p' es el número de
        columnas.

    Retorna:
    --------
    numpy.ndarray
        Una matriz bidimensional de forma (n, p) que representa el resultado de
        la multiplicación de Mat1 por Mat2.

    Ejemplo:
    --------
    >>> Mat1 = np.array([[1, 2, 3], [4, 5, 6]])
    >>> Mat2 = np.array([[7, 8], [9, 10], [11, 12]])
    >>> MultMat(Mat1, Mat2)
    array([[ 58.,  64.],
           [139., 154.]])
    """
    # Inicializa una matriz de ceros con las dimensiones adecuadas
    Mat3 = np.zeros((Mat1.shape[0], Mat2.shape[1]))

    # Itera sobre cada fila de la primera matriz
    for row in range(Mat1.shape[0]):
        # Itera sobre cada columna de la segunda matriz
        for col in range(Mat2.shape[1]):
            # Realiza la multiplicación y suma los productos
            for aux in range(Mat2.shape[0]):
                Mat3[row, col] += Mat1[row, aux] * Mat2[aux, col]

    # Devuelve la matriz resultante
    return Mat3


A=MultMat(R,R_t)
print(A)



# Comparación de 24c con los demás:

Es un proceso más tardado debido a la cantidad tan grande de procesos que se ejecutan, en este caso la mejor opción sería 24b ya que ocupa menos memoria y es más precisa
